### 查询 userName 历史记录
GET http://127.0.0.1:8443/AGE-API/history?userName=test

### 更新 userName 历史记录
POST http://127.0.0.1:8443/AGE-API/history
Content-Type: application/json

{
  "userName": "test",
  "creationTime": "2023-01-01 00:00:00",
  "updateTime": "2023-01-01 00:00:00",
  "data": []
}

### 删除 userName 历史记录
DELETE http://127.0.0.1:8443/AGE-API/history?userName=test



